### ISSUE TITLE
ERROR:  missing data for column "brand_name"

### ISSUE THREAD

**Issue by kzhangworks** [dbmi-pitt/faersdbstats#5]
Hello, I get the following error when executing the script **load_eu_drug_name_active_ingredient.sql**, the data look good in the file EU_registered_drugs_by_active_ingredient_utf8.txt,  does anybody have any idea to fix this error?

```
ERROR:  missing data for column "brand_name"
CONTEXT:  COPY eu_drug_name_active_ingredient, line 2: ""11-(2-pyrrolidin-1-yl-ethoxy)-14,19-dioxa-5,7,26-triaza-tetracyclo[19.3.1.1(2,6).1(8,12)] heptacosa..."
SQL state: 22P04
```

**Comment by wolfderby** [comment]
I'm going to look into this more thoroughly but I had in my notes that I added "WITH NULL AS 'null';" to the end of the COPY statement.

**Comment by kzhangworks** [comment]
@wolfderby Thank you! I wrote a node.js script to load all data of load_eu_drug_name_active_ingredient.sql into the database, I can share it with you if you need it. 
Do you have steps or notes to do the following prerequisite?

```
•	Load the latest available OHDSI CDMV5 Vocabulary tables into a separate PostgreSQL schema (e.g. cdmv5). The vocabulary data files and the PostgreSQL table load scripts are available from the  [OHDSI Athena website](http://www.ohdsi.org/web/athena/)  On the Athena website vocabulary download page keep the pre-selected vocabularies and also select the MedDRA vocabulary (review the EULA link for MedDRA).
```

**Comment by rkboyce** [comment]
Hi @kzhangworks - thanks for offering to share the node.js script. We are in the process of migrating to pentaho community version workflows so would not be able to use node.js. We will share our workflows publicly once completed and tested. 

The vocabulary download process is documented in a couple of places 

- https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html
- https://www.ohdsi.org/analytic-tools/athena-standardized-vocabularies/
-  https://athena.ohdsi.org/search-terms/start

You will have to email the folks who run Athena and pass on your EULA for MedDRA before they can include it in a vocab download. Then, load the DDL and data into a schema named e.g., 'vocabulary' into the same DBMS as your project.
